version: '3'

services:
  db:
    image: postgres:15
    restart: always
    container_name: ph8-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
