version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./ph8:/app/ph8
    env_file: .env
    environment:
      - DISABLE_CHROME_SANDBOX=true
    restart: always
    stdin_open: true
    tty: true
    command: ["sh", "-c", "find . -name '*.py' | entr -rs 'echo \"Initializing / Restarting due to changes...\" && python -m ph8.main'"]
  # chromadb:
  #   image: chromadb
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: chromadb
  #     MYSQL_USER: chroma
  #     MYSQL_PASSWORD: chroma