[tool.poetry]
name = "ph8"
version = "0.2.0"
description = ""
authors = ["Alex Howard <thezanke@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
"discord.py" = "^2.3.2"
openai = "^0.28.0"
python-dotenv = "^1.0.0"
certifi = "^2023.7.22"
beautifulsoup4 = "^4.12.2"
tenacity = "^8.2.3"
langchain = "^0.0.308"

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.24.1"
reloadium = "^1.3.0"

[tool.poe.tasks]
start.script = "ph8.main:init"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"